name: playbazaar
description: "PlayBazaar is a social gaming platform where users can chat privately, 
   create public and private groups, and participate in online quizzes. It combines communication 
   and competitive games, with plans to expand into various types of games in the future."

# This line prevents accidental publishing to pub.dev, ideal for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

  # The version and build number for your app are defined here. Format: 1.2.43+build.
  # They can be overridden using --build-name and --build-number in Flutter build.
  # Android uses them as versionName and versionCode, iOS as CFBundleShortVersionString and CFBundleVersion,
# and Windows for product/file versions.

version: 1.0.0+20 # This is the app version

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  typed_data: ^1.3.0
  firebase_core_platform_interface: ^6.0.0
  adaptive_dialog: ^2.2.0
  firebase_core: ^4.1.0
  firebase_auth: ^6.0.2
  cloud_firestore: ^6.0.1
  keyboard_dismisser: ^3.0.0
  validators: ^3.0.0
  avatar_glow: ^3.0.1
  async: ^2.11.0
  grouped_list: ^6.0.0
  intl: ^0.20.2
  shared_preferences: ^2.0.15
  email_validator: ^3.0.0
  provider: ^6.0.5
  image_picker: ^1.0.0
  font_awesome_flutter: ^10.4.0
  get: ^4.6.5
  flutter_advanced_switch: ^3.0.1
  encrypt: ^5.0.3
  just_audio: ^0.10.4
  permission_handler: ^12.0.0+1
  flutter_dotenv: ^6.0.0
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.0
  flutter_local_notifications: ^19.1.0
  firebase_messaging: ^16.0.1
  string_similarity: ^2.1.1
  cupertino_icons: ^1.0.8 # for ios style icons and fonts
  google_mobile_ads: ^6.0.0
  flutter_secure_storage: ^9.2.4
  googleapis: ^15.0.0
  googleapis_auth: ^2.0.0
  #firebase_app_check: ^0.3.1+7
  device_info_plus: ^12.1.0
  http: ^1.2.2
  path: ^1.9.0
  flutter_svg: ^2.0.16
  lottie: ^3.3.0
  analyzer: ^8.1.1
  #flame: ^1.25.0
  equatable: ^2.0.7
  flutter_native_splash: ^2.4.6
  app_tracking_transparency: ^2.0.6+1
  flutter_launcher_icons: ^0.14.3
  hive_ce: ^2.15.1
  hive_ce_flutter: ^2.3.3
  flutter_riverpod: ^3.0.3
  go_router: ^17.0.0
  advertising_id: ^2.7.1
  package_info_plus: ^9.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  #The "flutter_lints" package offers recommended lints for good coding,
  #activated in analysis_options.yaml, where you can customize them.
  hive_ce_generator: ^1.10.0
  flutter_lints: ^6.0.0
  build_runner: ^2.4.6


# flutter pub run flutter_launcher_icons
flutter_launcher_icons:
  image_path: "assets/icons/play_bazaar_logo.png"

  # Android configuration
  android: "launcher_icon"
  min_sdk_android: 24
  adaptive_icon_background: "#000000"  # Black background for adaptive icon
  adaptive_icon_foreground: "assets/icons/play_bazaar_logo.png"

  android_icon_size: 48

  # iOS configuration
  ios: true
  image_path_ios: "assets/icons/icon.png"
  remove_alpha_channel_ios: true

  web:
    generate: false
  windows:
    generate: false
  macos:
    generate: false


flutter_native_splash:
  color: "#ffffff"
  image: assets/icons/splash_screen_960x960.png
  android: true
  ios: true
  web: false

  android_12:
    image: assets/icons/splash_screen_960x960.png
    color: "#ffffff"
    icon_background_color: "#ffffff"


# The following section is specific to Flutter packages.
flutter:
  # To ensure that Material Icons font can be used material icons class.
  uses-material-design: true

  # Assets section: here you can defines your image path. For more see the link below:
  # https://flutter.dev/to/resolution-aware-images
  # https://flutter.dev/to/asset-from-package
  assets:
    - assets/icons/
    - assets/images/
    - assets/sounds/
    - assets/sounds/button/
    - assets/sounds/sad/baby_no_no_no.mp3
    - assets/sounds/end_game/
    - assets/config/
    - assets/config/.env
    - assets/fonts/
    - assets/icons/splash_screen_960x960.png
    - assets/games/hangman/
    - assets/games/ludo/
    - assets/games/ludo/dice/
    - assets/games/ludo/dice/blue/
    - assets/games/ludo/dice/green/
    - assets/games/ludo/dice/red/
    - assets/games/ludo/dice/yellow/



  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
  fonts:
    - family: Schyler
      fonts:
        - asset: assets/fonts/add_person.ttf